language: node_js
python:
  - 2.7
node_js:
  - 10
before_install:
  - sudo pip install -r requirements.txt
  - gem install bundler -v 1.17.3
  - openssl aes-256-cbc -K $encrypted_34ecf922df88_key -iv $encrypted_34ecf922df88_iv
    -in credentials.tar.gz.enc -out credentials.tar.gz -d
  - tar -xzf credentials.tar.gz
  - npm run test
after_success:
  - npm run build
deploy:
  provider: gae
  skip_cleanup: true
  keyfile: client-secret.json
  project: mysudokuhelper
  default: true
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(master|react)$
# safelist
branches:
  only:
    - master
    - react
