language: python
python:
  - 3.6
install:
  - pip install -r requirements.txt
script:
  - pytest
before_install:
- openssl aes-256-cbc -K $encrypted_34ecf922df88_key -iv $encrypted_34ecf922df88_iv
  -in credentials.tar.gz.enc -out credentials.tar.gz -d
- tar -xzf credentials.tar.gz
deploy:
  provider: gae
  skip_cleanup: true
  keyfile: client-secret.json
  project: mysudokuhelper
  default: true
  on:
    all_branches: true
