language: nodejs
python:
  - 3.6
node_js:
  - 10
before_install:
  - sudo pip install -r requirements.txt
  - gem install bundler -v 1.17.3
  - openssl aes-256-cbc -K $encrypted_34ecf922df88_key -iv $encrypted_34ecf922df88_iv
    -in credentials.tar.gz.enc -out credentials.tar.gz -d
  - tar -xzf credentials.tar.gz
deploy:
  provider: gae
  skip_cleanup: true
  keyfile: client-secret.json
  project: mysudokuhelper
  default: true
  on: master
# safelist
branches:
  only:
    - master
    - react
